1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]


In [1]:
import numpy as np
num_list = [12.23, 13.32, 100, 36.32]
num_array = np.array(num_list)
print(num_array)

[ 12.23  13.32 100.    36.32]


2.Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


In [2]:
arr = np.arange(2,11).reshape(3,3)
print(arr)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


In [3]:
arr = np.zeros(10)
print("Size 10 1D array having all element as zero : ")
print(arr)
arr[6] = 11
print("After modifying 6th index element : ")
print(arr)

Size 10 1D array having all element as zero : 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After modifying 6th index element : 
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4.Write a Python program to reverse an array (first element becomes last).


In [4]:
arr = np.arange(12,38)
print("Original Array : ")
print(arr)
print("Reverse Array : ")
print(arr[::-1])

Original Array : 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse Array : 
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5.Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [5]:
arr = np.ones([5,5])
print("Original Array : \n")
print(arr)
arr[1:-1 , 1:-1] = 0
print("\nExpected Ouput : \n")
print(arr)

Original Array : 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Expected Ouput : 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6.Write a Python program to add a border (filled with 0's) around an existing array.

In [6]:
arr = np.ones((3,3))
print("Original array:")
print(arr)
print("0 on the border and 1 inside in the array")
arr = np.pad(arr,1)
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7.Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [7]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print("Expected Ouput : \n")
print(arr)

Expected Ouput : 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8.Write a Python program to convert a list and tuple into arrays.

In [8]:
list = [1,2,3,4,5,6,7,8]
tuple_ele = ([8,4,6],[1,2,3])
list_to_arr = np.array(list,dtype=int)
tuple_to_arr = np.array(tuple_ele)
print("List to array : \n")
print(list_to_arr)
print("\nTuple to array : \n")
print(tuple_to_arr)

List to array : 

[1 2 3 4 5 6 7 8]

Tuple to array : 

[[8 4 6]
 [1 2 3]]


9.Write a Python program to append values to the end of an array.

In [9]:
arr = np.array([10,20,30],dtype=int)
print("Old Array : ")
print(arr)
arr2 = np.array([30,40,50,60,70,80],dtype=int)
new_arr = np.append(arr , arr2)
new_arr = np.append(new_arr,90)
print("New Array : ")
print(new_arr)

Old Array : 
[10 20 30]
New Array : 
[10 20 30 30 40 50 60 70 80 90]


10.Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [10]:
complex_num_list =  [1.00000000 + 0.j , 0.70710678 + 0.70710678j]
comple_num_arr = np.array(complex_num_list)
real_arr = []
img_arr = []
for i in comple_num_arr:
    real_arr.append(i.real)
    img_arr.append(i.imag)
print("Real part of Array : ")
print(np.array(real_arr))
print("Imaginary part of Array : ")
print(np.array(img_arr))

Real part of Array : 
[1.         0.70710678]
Imaginary part of Array : 
[0.         0.70710678]


11.Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [11]:
arr = np.array([1,2,3],dtype=int)
arr1 = np.array(["Madhavee","Kadivar"," "])
print(f"Size of the array : {arr.size}")
print(f"Length of one array element in bytes : {arr1.itemsize}")
print(f"Total bytes consumed by the elements of the array : {arr.nbytes}")

Size of the array : 3
Length of one array element in bytes : 32
Total bytes consumed by the elements of the array : 12


12.Write a Python program to find common values between two arrays.

In [12]:
array1 =  np.array([0,10,20,40,60],dtype=int)
array2 = [10, 30, 40]

common_ele = np.intersect1d(array1,array2)
print(f"Common element between {array1} and {array2} are : {common_ele}")

Common element between [ 0 10 20 40 60] and [10, 30, 40] are : [10 40]


13.Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [13]:
array1 =  np.array([0,10,20,40,60,80],dtype=int)
array2 = [10, 30, 40 ,50,70,90]

set_difference = np.setdiff1d(array1,array2)
print(f"Set difference between {array1} and {array2} are : {set_difference}")

Set difference between [ 0 10 20 40 60 80] and [10, 30, 40, 50, 70, 90] are : [ 0 20 60 80]


14.Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [14]:
array1 =  np.array([ 0,10,20,40,60,80 ],dtype=int)
array2 = [10, 30, 40, 50, 70]

set_exclusive_or = np.setxor1d(array1,array2)
print(f"Set exclusive or between {array1} and {array2} are : {set_exclusive_or}")

Set exclusive or between [ 0 10 20 40 60 80] and [10, 30, 40, 50, 70] are : [ 0 20 30 50 60 70 80]


15.Write a Python program compare two arrays using numpy.

In [15]:
a = np.array([1,2] , dtype=int)
b = np.array([4,5] , dtype=int)

print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


15.Write a Python program to save a NumPy array to a text file.

In [16]:
arr = np.array([1,2,3,4,5])
with open("file.txt","w") as f:
    f.write(str(arr))
with open("file.txt","r") as f:
    content = f.read()  
print("\nContent in file.txt:\n", content)

np.savetxt("file1.txt", arr)
content = np.loadtxt("file1.txt")
print("\nContent in file1.txt:\n", content)


Content in file.txt:
 [1 2 3 4 5]

Content in file1.txt:
 [1. 2. 3. 4. 5.]


16.Write a Python program to create a contiguous flattened array.

In [17]:
arr = np.array([[[10, 20, 30],[20, 40, 50]]], dtype=int)
print(arr)
flattened_arr = np.ravel(arr)
print(f"\nFlattened array: {flattened_arr}")

[[[10 20 30]
  [20 40 50]]]

Flattened array: [10 20 30 20 40 50]


17.Write a Python program to change the data type of an array.

In [18]:
arr = np.array([[2, 4, 6],[6, 8, 10]])
print(arr)
print(f"Data type of the array is: {arr.dtype}")
print("\nNew Type: float64")
arr = arr.astype('bool')
print(arr)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array is: int32

New Type: float64
[[ True  True  True]
 [ True  True  True]]


18.Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [19]:
arr = np.identity(3)
print(arr)
arr1 = np.eye(3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19.Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]

[ 1. 1. 1.]]


In [20]:
arr = np.ones([4,3])
arr = np.tril(arr)
print(arr)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


20.Write a Python program to concatenate two 2-dimensional arrays.

In [21]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]] , dtype=int)
arr2 = np.array([[0, 2, 4], [6, 8, 10]] , dtype=int)
new_arr = np.concatenate((arr1,arr2) , axis = 1)
print(new_arr)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21.Write a Python program to make an array immutable (read-only).

In [22]:
arr = np.array((1,2,3,4,5),dtype=int)
arr.flags.writeable = False
print(arr)
arr[0] = 9
print(arr)

[1 2 3 4 5]


ValueError: assignment destination is read-only

22.Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.

In [ ]:
arr = np.arange(12).reshape(3,4)
number = 3
arr = arr * number
print(arr)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23.Write a Python program to convert a NumPy array into Python list structure.

In [ ]:
numpy_arr  = np.arange(0,6).reshape(3,2)
print("Original array elements : ")
print(numpy_arr)
list = numpy_arr.tolist()
print("Array to list : ")
print(list)

Original array elements : 
[[0 1]
 [2 3]
 [4 5]]
Array to list : 
[[0, 1], [2, 3], [4, 5]]


24.Write a Python program to convert a NumPy array into Python list structure.

In [ ]:
list  = [ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478]
arr = np.array(list,dtype=float)
print("Original Array Elements : ")
print(arr)
print("Array with precision value 3 : ")
arr = arr.round(3)
print(arr)


Original Array Elements : 
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Array with precision value 3 : 
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25.Write a Python program to suppresses the use of scientific notation for small numbers in numpy array

In [ ]:
arr = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print("Original Array Elements : ")
print(arr)
print("Array with precision value 3 : ")
np.set_printoptions(precision = 3 ,suppress=True)
print(arr)

Original Array Elements : 
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Array with precision value 3 : 
[   0.       1.6   1200.       0.235]


26.Write a Python program to how to add an extra column to an numpy array.

In [ ]:
arr = np.array([[ 10, 20, 30],[ 40, 50, 60 ]])
print("Original array : ")
print(arr)
new_array = np.array([[100],[200]])
arr = np.column_stack((arr, new_array))
# arr = np.append(arr,new_array,axis = 1)
print("Array after adding column : ")
print(arr)

Original array : 
[[10 20 30]
 [40 50 60]]
Array after adding column : 
[[ 10  20  30 100]
 [ 40  50  60 200]]


27.Write a Python program to remove specific elements in a numpy array.

In [ ]:
arr = np.array([ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original Array :")
print(arr)
arr = np.delete(arr, [0,3,4])
print("After deleting first,fourth and fifth element : ")
print(arr)


Original Array :
[ 10  20  30  40  50  60  70  80  90 100]
After deleting first,fourth and fifth element : 
[ 20  30  60  70  80  90 100]
